# create a virtual machine with Linux Ubuntu 16.04
# ubuntu/xenial64

Vagrant.configure("2") do |config|

 # choose the os/box/distro
 config.vm.box = "ubuntu/xenial64"
 config.vm.network "private_network", ip: "192.168.56.210"
 config.vm.network "forwarded_port", guest: 82, host: 8282

#Vagrant destroy
#Vagrant up
#Vagrant reload

end





